require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.plenary"
spec "user.mini"
spec "user.autopairs"
spec "user.comment"
spec "user.devicons"
spec "user.whichkey"
spec "user.breadcrumbs"
spec "user.navic"

spec "user.noice"
spec "user.indentline"
spec "user.telescope"
spec "user.treesitter"

spec "user.gitsigns"
spec "user.harpoon"
spec "user.illuminate"

spec "user.trouble"
spec "user.lspconfig"
spec "user.mason"
-- spec "user.project"

spec "user.cmp"
spec "user.nvim-dap"

spec "user.nvimtree"
spec "user.lualine"

require "user.lazy"
