- name: Copy Alias conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/root/alias"
    dest: "{{ HOME_DIR }}/.alias"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Copy Bashrc conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/root/bashrc"
    dest: "{{ HOME_DIR }}/.bashrc"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Load OhMyZSH plugins
  ansible.builtin.shell:
    cmd: yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    chdir: "{{ HOME_DIR }}/"

- name: Copy Zshrc conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/root/zshrc"
    dest: "{{ HOME_DIR }}/.zshrc"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Copy Zshrc (OhMyZSH p10K) conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/root/p10k.zsh"
    dest: "{{ HOME_DIR }}/.p10k.zsh"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Copy Tmux conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/tmux/"
    dest: "{{ HOME_DIR }}/.config/tmux"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Copy Nvim conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/nvim/"
    dest: "{{ HOME_DIR }}/.config/nvim"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Copy Kitty conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/kitty/"
    dest: "{{ HOME_DIR }}/.config/kitty"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Copy SSH conf
  ansible.builtin.copy:
    src: "{{ RESS_DIR }}/config/ssh/"
    dest: "{{ HOME_DIR }}/.ssh"
    mode: '0644'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Change Permission Private SSH key 1
  ansible.builtin.file:
    path: "{{ HOME_DIR }}/.ssh/key_ed25519_github"
    mode: '0600'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"

- name: Change Permission Private SSH key 2
  ansible.builtin.file:
    path: "{{ HOME_DIR }}/.ssh/key_ed25519_global"
    mode: '0600'
    owner: "{{ HOME_USR }}"
    group: "{{ HOME_USR }}"



