- name: Manage Repositories
  ansible.builtin.include_tasks:
    file: repositories.yml

- name: Manage Packages
  ansible.builtin.include_tasks:
    file: packages.yml

- name: Manage KDE Config
  ansible.builtin.include_tasks:
    file: kde_config.yml

