
- name: Load Vars Packages File
  ansible.builtin.include_vars:
    file: packages_removes.yml
    name: packages_rem


- name: Remove Packages
  community.general.zypper:
    name: "{{ item }}"
    clean_deps: true
    state: absent
    disable_recommends: false
  with_items:
    - "{{ packages_rem.packages }}"

- name: Lock Remove Packages
  ansible.builtin.shell:
    cmd: zypper addlock "{{ item }}"
  become: true
  become_user: "{{ HOME_USR }}"
  with_items:
    - "{{ packages_rem.packages }}"

