
- name: Load Vars Packages Flatpak File
  ansible.builtin.include_vars:
    file: packages_flatpak.yml
    name: packages_fp


- name: Add the flathub flatpak repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo


- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages_fp.packages }}"

